// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/bootstrap.proto

package kronospb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BootstrapRequest struct {
	ExpectedNodeCount    int32    `protobuf:"varint,1,opt,name=expectedNodeCount,proto3" json:"expectedNodeCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootstrapRequest) Reset()         { *m = BootstrapRequest{} }
func (m *BootstrapRequest) String() string { return proto.CompactTextString(m) }
func (*BootstrapRequest) ProtoMessage()    {}
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bootstrap_a9588ac605391393, []int{0}
}
func (m *BootstrapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootstrapRequest.Unmarshal(m, b)
}
func (m *BootstrapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootstrapRequest.Marshal(b, m, deterministic)
}
func (dst *BootstrapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootstrapRequest.Merge(dst, src)
}
func (m *BootstrapRequest) XXX_Size() int {
	return xxx_messageInfo_BootstrapRequest.Size(m)
}
func (m *BootstrapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BootstrapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BootstrapRequest proto.InternalMessageInfo

func (m *BootstrapRequest) GetExpectedNodeCount() int32 {
	if m != nil {
		return m.ExpectedNodeCount
	}
	return 0
}

type BootstrapResponse struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=clusterId,proto3" json:"clusterId,omitempty"`
	NodeCount            int32    `protobuf:"varint,2,opt,name=nodeCount,proto3" json:"nodeCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootstrapResponse) Reset()         { *m = BootstrapResponse{} }
func (m *BootstrapResponse) String() string { return proto.CompactTextString(m) }
func (*BootstrapResponse) ProtoMessage()    {}
func (*BootstrapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bootstrap_a9588ac605391393, []int{1}
}
func (m *BootstrapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootstrapResponse.Unmarshal(m, b)
}
func (m *BootstrapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootstrapResponse.Marshal(b, m, deterministic)
}
func (dst *BootstrapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootstrapResponse.Merge(dst, src)
}
func (m *BootstrapResponse) XXX_Size() int {
	return xxx_messageInfo_BootstrapResponse.Size(m)
}
func (m *BootstrapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BootstrapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BootstrapResponse proto.InternalMessageInfo

func (m *BootstrapResponse) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *BootstrapResponse) GetNodeCount() int32 {
	if m != nil {
		return m.NodeCount
	}
	return 0
}

func init() {
	proto.RegisterType((*BootstrapRequest)(nil), "kronospb.BootstrapRequest")
	proto.RegisterType((*BootstrapResponse)(nil), "kronospb.BootstrapResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BootstrapClient is the client API for Bootstrap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BootstrapClient interface {
	Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error)
}

type bootstrapClient struct {
	cc *grpc.ClientConn
}

func NewBootstrapClient(cc *grpc.ClientConn) BootstrapClient {
	return &bootstrapClient{cc}
}

func (c *bootstrapClient) Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error) {
	out := new(BootstrapResponse)
	err := c.cc.Invoke(ctx, "/kronospb.Bootstrap/Bootstrap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BootstrapServer is the server API for Bootstrap service.
type BootstrapServer interface {
	Bootstrap(context.Context, *BootstrapRequest) (*BootstrapResponse, error)
}

func RegisterBootstrapServer(s *grpc.Server, srv BootstrapServer) {
	s.RegisterService(&_Bootstrap_serviceDesc, srv)
}

func _Bootstrap_Bootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootstrapServer).Bootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kronospb.Bootstrap/Bootstrap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootstrapServer).Bootstrap(ctx, req.(*BootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bootstrap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kronospb.Bootstrap",
	HandlerType: (*BootstrapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bootstrap",
			Handler:    _Bootstrap_Bootstrap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/bootstrap.proto",
}

func init() { proto.RegisterFile("pb/bootstrap.proto", fileDescriptor_bootstrap_a9588ac605391393) }

var fileDescriptor_bootstrap_a9588ac605391393 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x48, 0xd2, 0x4f,
	0xca, 0xcf, 0x2f, 0x29, 0x2e, 0x29, 0x4a, 0x2c, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0xc8, 0x2e, 0xca, 0xcf, 0xcb, 0x2f, 0x2e, 0x48, 0x52, 0x72, 0xe0, 0x12, 0x70, 0x82, 0x49, 0x06,
	0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xe9, 0x70, 0x09, 0xa6, 0x56, 0x14, 0xa4, 0x26, 0x97,
	0xa4, 0xa6, 0xf8, 0xe5, 0xa7, 0xa4, 0x3a, 0xe7, 0x97, 0xe6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0xb0, 0x06, 0x61, 0x4a, 0x28, 0xf9, 0x73, 0x09, 0x22, 0x99, 0x50, 0x5c, 0x90, 0x9f, 0x57, 0x9c,
	0x2a, 0x24, 0xc3, 0xc5, 0x99, 0x9c, 0x53, 0x5a, 0x5c, 0x92, 0x5a, 0xe4, 0x99, 0x02, 0xd6, 0xca,
	0x19, 0x84, 0x10, 0x00, 0xc9, 0xe6, 0xc1, 0x0d, 0x66, 0x02, 0x1b, 0x8c, 0x10, 0x30, 0x0a, 0xe6,
	0xe2, 0x84, 0x1b, 0x28, 0xe4, 0x86, 0xcc, 0x91, 0xd2, 0x83, 0xb9, 0x5b, 0x0f, 0xdd, 0xd1, 0x52,
	0xd2, 0x58, 0xe5, 0x20, 0xce, 0x51, 0x62, 0x70, 0xe2, 0x8a, 0x82, 0xfb, 0x39, 0x89, 0x0d, 0x1c,
	0x08, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0xb3, 0xcb, 0xdf, 0x1a, 0x01, 0x00, 0x00,
}
