// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/gossip.proto

package kronospb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	// node_id is the id of the node that sent the request
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// addr is the address of the node that sent the request
	AdvertisedHostPort string `protobuf:"bytes,2,opt,name=advertised_host_port,json=advertisedHostPort,proto3" json:"advertised_host_port,omitempty"`
	// cluster_id is the id of the cluster that sent the request
	ClusterId            string           `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	GossipMap            map[string]*Info `protobuf:"bytes,4,rep,name=gossipMap,proto3" json:"gossipMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_gossip_3eb9a7d8169e0992, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Request) GetAdvertisedHostPort() string {
	if m != nil {
		return m.AdvertisedHostPort
	}
	return ""
}

func (m *Request) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *Request) GetGossipMap() map[string]*Info {
	if m != nil {
		return m.GossipMap
	}
	return nil
}

type Info struct {
	// timestamp is the time at which the info was added
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// data is the actual data
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_gossip_3eb9a7d8169e0992, []int{1}
}
func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (dst *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(dst, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Info) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response struct {
	// node_id is the id of the node that sent the response
	NodeId               string           `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Data                 map[string]*Info `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_gossip_3eb9a7d8169e0992, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Response) GetData() map[string]*Info {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "kronospb.Request")
	proto.RegisterMapType((map[string]*Info)(nil), "kronospb.Request.GossipMapEntry")
	proto.RegisterType((*Info)(nil), "kronospb.Info")
	proto.RegisterType((*Response)(nil), "kronospb.Response")
	proto.RegisterMapType((map[string]*Info)(nil), "kronospb.Response.DataEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GossipClient is the client API for Gossip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GossipClient interface {
	Gossip(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type gossipClient struct {
	cc *grpc.ClientConn
}

func NewGossipClient(cc *grpc.ClientConn) GossipClient {
	return &gossipClient{cc}
}

func (c *gossipClient) Gossip(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/kronospb.Gossip/Gossip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GossipServer is the server API for Gossip service.
type GossipServer interface {
	Gossip(context.Context, *Request) (*Response, error)
}

func RegisterGossipServer(s *grpc.Server, srv GossipServer) {
	s.RegisterService(&_Gossip_serviceDesc, srv)
}

func _Gossip_Gossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).Gossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kronospb.Gossip/Gossip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).Gossip(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gossip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kronospb.Gossip",
	HandlerType: (*GossipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Gossip",
			Handler:    _Gossip_Gossip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/gossip.proto",
}

func init() { proto.RegisterFile("pb/gossip.proto", fileDescriptor_gossip_3eb9a7d8169e0992) }

var fileDescriptor_gossip_3eb9a7d8169e0992 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0xfd, 0xd2, 0xf4, 0x6b, 0x9b, 0xa9, 0x54, 0x1d, 0x04, 0x4b, 0xa9, 0x50, 0x82, 0x87, 0x9e,
	0xa2, 0xd6, 0x4b, 0x51, 0xf0, 0x20, 0x4a, 0x2d, 0x28, 0xc8, 0x1e, 0xbd, 0x94, 0xad, 0xbb, 0x6a,
	0x68, 0x9b, 0x5d, 0x77, 0xa7, 0x85, 0x1e, 0xfd, 0x23, 0xfe, 0x56, 0xc9, 0xa6, 0x49, 0x94, 0x82,
	0x17, 0x6f, 0xb3, 0x6f, 0xde, 0x3c, 0xde, 0x7b, 0x2c, 0xec, 0xea, 0xe9, 0xc9, 0xab, 0xb2, 0x36,
	0xd6, 0x91, 0x36, 0x8a, 0x14, 0x36, 0x66, 0x46, 0x25, 0xca, 0xea, 0x69, 0xf8, 0x51, 0x81, 0x3a,
	0x93, 0xef, 0x4b, 0x69, 0x09, 0x0f, 0xa1, 0x9e, 0x28, 0x21, 0x27, 0xb1, 0x68, 0x7b, 0x3d, 0xaf,
	0x1f, 0xb0, 0x5a, 0xfa, 0x1c, 0x0b, 0x3c, 0x85, 0x03, 0x2e, 0x56, 0xd2, 0x50, 0x6c, 0xa5, 0x98,
	0xbc, 0x29, 0x4b, 0x13, 0xad, 0x0c, 0xb5, 0x2b, 0x8e, 0x85, 0xe5, 0xee, 0x4e, 0x59, 0x7a, 0x54,
	0x86, 0xf0, 0x08, 0xe0, 0x79, 0xbe, 0xb4, 0x24, 0x4d, 0xaa, 0xe6, 0x3b, 0x5e, 0xb0, 0x41, 0xc6,
	0x02, 0xaf, 0x20, 0xc8, 0xfc, 0x3c, 0x70, 0xdd, 0xae, 0xf6, 0xfc, 0x7e, 0x73, 0xd0, 0x8b, 0x72,
	0x4f, 0xd1, 0xc6, 0x4f, 0x34, 0xca, 0x29, 0xb7, 0x09, 0x99, 0x35, 0x2b, 0x4f, 0x3a, 0xf7, 0xd0,
	0xfa, 0xb9, 0xc4, 0x3d, 0xf0, 0x67, 0x72, 0xbd, 0xf1, 0x9d, 0x8e, 0x78, 0x0c, 0xff, 0x57, 0x7c,
	0xbe, 0x94, 0xce, 0x65, 0x73, 0xd0, 0x2a, 0xf5, 0xc7, 0xc9, 0x8b, 0x62, 0xd9, 0xf2, 0xa2, 0x32,
	0xf4, 0xc2, 0x21, 0x54, 0x53, 0x08, 0xbb, 0x10, 0x50, 0xbc, 0x90, 0x96, 0xf8, 0x42, 0x3b, 0x25,
	0x9f, 0x95, 0x00, 0x22, 0x54, 0x05, 0x27, 0xee, 0xe4, 0x76, 0x98, 0x9b, 0xc3, 0x4f, 0x0f, 0x1a,
	0x4c, 0x5a, 0xad, 0x12, 0x2b, 0x7f, 0xab, 0x2f, 0xbf, 0x4c, 0x83, 0x76, 0xbf, 0x07, 0xcd, 0x4e,
	0xa3, 0x1b, 0x4e, 0x3c, 0x0b, 0xe9, 0x98, 0x9d, 0x11, 0x04, 0x05, 0xf4, 0x97, 0x68, 0x83, 0x4b,
	0xa8, 0x65, 0x45, 0xe1, 0x59, 0x31, 0xed, 0x6f, 0x35, 0xdd, 0xc1, 0x6d, 0x4f, 0xe1, 0xbf, 0x6b,
	0x78, 0x2a, 0xfe, 0xc9, 0xb4, 0xe6, 0x3e, 0xce, 0xf9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x60,
	0x2f, 0xc7, 0x0c, 0x4b, 0x02, 0x00, 0x00,
}
